### ISSUE TITLE
can't install versions >= v1.1.0

### ISSUE THREAD

**Issue by grimm26** [iul1an/asdf-tfswitch#3]
https://github.com/iul1an/asdf-tfswitch/pull/2 didn't seem to solve the issue. I'm using mise so I haven't tried asdf directly

```
❯ mise use --yes --global tfswitch@v1.1.1
curl: (22) The requested URL returned error: 404
asdf-tfswitch: Could not download https://github.com/warrensbox/terraform-switcher/releases/download/1.1.1/terraform-switcher_1.1.1_linux_amd64.tar.gz
mise ~/.local/share/mise/plugins/tfswitch/bin/download failed
* Downloading tfswitch release 1.1.1...
curl: (22) The requested URL returned error: 404
asdf-tfswitch: Could not download https://github.com/warrensbox/terraform-switcher/releases/download/1.1.1/terraform-switcher_1.1.1_linux_amd64.tar.gz
```

I'm assuming asdf would have the same issue?

**Comment by iul1an** [comment]
I also use `mise/rtx`, but `asdf` probably has the same issue.
Your change was valid in terms of Bash scripting. However, `mise` removes the leading "v" when it calls the download script, that's why the download fails with 404. More details here: https://github.com/jdx/mise/issues/1865

We need to find a better way to fix the issue, maybe the logic in the `download_release` function.

**Comment by grimm26** [comment]
@iul1an I think https://github.com/iul1an/asdf-tfswitch/pull/4 will do it

**Comment by iul1an** [comment]
@grimm26 Since your new [PR](https://github.com/iul1an/asdf-tfswitch/pull/4) solves the issue independently, there's no need to keep [this change](https://github.com/iul1an/asdf-tfswitch/pull/5/files), so I reverted it to maintain consistency between `mise` and manual execution of the plugin when doing development.
Everything works fine now. Thank you again for the contribution :)
